// =============================================================================
// CONTENT LOADER (client-safe)
//
// Everything on this site is edited in the CMS at /admin and stored as JSON in
// `content/`. This file loads the collections and re-exports them under the same
// names the components have always used, so nothing downstream had to change.
//
// IMPORTANT — why collections are imported here but pages are not:
// This module is imported by components/ClientBits.tsx, which is "use client".
// Anything in this import chain is bundled for the browser, so it must not touch
// the filesystem. Collections are therefore plain `import`s of single JSON files.
// PAGES live in `lib/pages.server.ts` instead, where fs is allowed, because they
// are one-file-per-page so editors can add and delete whole pages.
//
// Editors: do not edit this file. Content is at /admin.
// =============================================================================

import { resolve } from "./content";
import navigationData from "@/content/navigation.json";
import beforeAfterData from "@/content/collections/before-after.json";
import brewProductsData from "@/content/collections/brew-products.json";
import brewingMethodsData from "@/content/collections/brewing-methods.json";
import cleanGreenData from "@/content/collections/cleangreen-services.json";
import directoryData from "@/content/collections/directory.json";
import eventsData from "@/content/collections/events.json";
import homeHeroData from "@/content/collections/home-hero.json";
import internsData from "@/content/collections/interns.json";
import membershipTiersData from "@/content/collections/membership-tiers.json";
import newsData from "@/content/collections/news.json";
import partnersData from "@/content/collections/partners.json";
import projectPinsData from "@/content/collections/project-pins.json";
import supportersData from "@/content/collections/supporters.json";
import teamData from "@/content/collections/team.json";
import testimonialsData from "@/content/collections/testimonials.json";

import type {
  ActiveNav,
  BeforeAfterPair,
  BrewProduct,
  BrewVariant,
  Card,
  DirectoryEntry,
  FeedEntry,
  HomeHeroSlide,
  MembershipTier,
  Partner,
  ProjectPin,
  Section,
  SitePage,
  SupporterLogo,
  TeamMember,
  Testimonial,
} from "./types";

export type {
  ActiveNav,
  BeforeAfterPair,
  BrewProduct,
  BrewVariant,
  Card,
  DirectoryEntry,
  FeedEntry,
  HomeHeroSlide,
  MembershipTier,
  Partner,
  ProjectPin,
  Section,
  SitePage,
  SupporterLogo,
  TeamMember,
  Testimonial,
};

export { siteConfig } from "./siteConfig";

// `resolve` swaps {{settings}} tokens for their live values — see lib/content.ts.
const load = <T,>(payload: { items: unknown[] }): T[] => resolve(payload.items) as T[];

// --- Navigation -------------------------------------------------------------

type NavLink = { label: string; href: string };
type NavGroup = { key: string; label: string; href: string; active: ActiveNav; items: NavLink[] };

export const navigation = navigationData as unknown as {
  groups: NavGroup[];
  simpleLinks: { label: string; href: string; active: ActiveNav }[];
  utilityLinks: NavLink[];
  donateCta: NavLink;
  footerColumns: { title: string; links: NavLink[] }[];
  aliases: Record<string, string>;
};

export const navGroups = navigation.groups;
export const aliases = navigation.aliases;

// --- Collections ------------------------------------------------------------

export const beforeAfterPairs = load<BeforeAfterPair>(beforeAfterData);
export const brewProducts = load<BrewProduct>(brewProductsData);
export const brewingMethods = load<Card>(brewingMethodsData);
export const cleanGreenServices = load<string>(cleanGreenData);
export const events = load<FeedEntry>(eventsData);
export const homeHeroSlides = load<HomeHeroSlide>(homeHeroData);
export const interns = load<TeamMember>(internsData);
export const leadership = load<TeamMember>(teamData);
export const membershipTiers = load<MembershipTier>(membershipTiersData);
export const news = load<FeedEntry>(newsData);
export const partners = load<Partner>(partnersData);
export const projectPins = load<ProjectPin>(projectPinsData);
export const serviceDirectory = load<DirectoryEntry>(directoryData);
export const supporterLogos = load<SupporterLogo>(supportersData);
export const testimonials = load<Testimonial>(testimonialsData);

export const partnerNames = partners.map((p) => p.name);
